// Code generated by "stringer -type LogLevel"; DO NOT EDIT

package glogger

import "fmt"

const loglevelName = "TRACEDEBUGINFOWARNERRORPANICFATAL"

var loglevelIndex = [...]uint8{0, 5, 10, 14, 18, 23, 28, 33}

func (i LogLevel) String() string {
	i -= -2
	if i < 0 || i >= LogLevel(len(loglevelIndex)-1) {
		return fmt.Sprintf("LogLevel(%d)", i+-2)
	}
	return loglevelName[loglevelIndex[i]:loglevelIndex[i+1]]
}
