// Code generated by "stringer -type LogLevel"; DO NOT EDIT.

package glogger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TRACE - -2]
	_ = x[DEBUG - -1]
	_ = x[INFO-0]
	_ = x[WARN-1]
	_ = x[ERROR-2]
	_ = x[PANIC-3]
	_ = x[FATAL-4]
}

const _LogLevel_name = "TRACEDEBUGINFOWARNERRORPANICFATAL"

var _LogLevel_index = [...]uint8{0, 5, 10, 14, 18, 23, 28, 33}

func (i LogLevel) String() string {
	i -= -2
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
